apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inference
  template:
    metadata:
      labels:
        app: inference
    spec:
      containers:
      - name: inference-container
        image: your-dockerhub-username/inference-pod:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
        - name: MODEL_CACHE
          value: "/models"
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP

